### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by jensjorisdecorte** [Alibaba-NLP/SeqGPT#1]
Hi, thank you for this exciting work. I want to try it out, but the link to huggingface doesn't work and I can't find the model weights.

**Comment by yiranyyu** [comment]
Sorry for the delay, we are still preparing the final hosts of the weight. A temporary hugging face [link](https://huggingface.co/Yirany/SeqGPT-560M/) is now available, hope it can be helpful for you!
