### ISSUE TITLE
非常好的项目，是llm背景下的一股清流啊

### ISSUE THREAD

**Issue by datalee** [Alibaba-NLP/SeqGPT#11]
您好，麻烦可以开源3b or 7b版本吗。万分感谢

**Comment by yiranyyu** [comment]
感谢关注！我们最近会把 1B7 模型权重开源到 modelscope，3B 和 7B 模型权重未来也可能会开源出来。

**Comment by JoshonSmith** [comment]
> 感谢关注！我们最近会把 1B7 模型权重开源到 modelscope，3B 和 7B 模型权重未来也可能会开源出来。

你好，1B7的模型权重开源了没有？modelscope没有搜到
