### ISSUE TITLE
Questions regarding the demo image

### ISSUE THREAD

**Issue by HolmesShuan** [Alibaba-NLP/SeqGPT#12]
Hi, great job! I have a minor concern regarding the demo image:
![image](https://github.com/Alibaba-NLP/SeqGPT/assets/16162739/e23a2ca3-0fdc-4d50-9736-9adac368d0d1)

How to understand the results of **Classify** given **Extradition, Process_start**? According to the definition of "Classification (CLS)" which "associates the entire input with a suitable subset of the given labels", it seems that the output should be "Extradition, Process_start". I appreciate any help you can provide.

**Comment by LouChao98** [comment]
Nice catch! We have fixed the error.
