### ISSUE TITLE
怎么下载模型啊

### ISSUE THREAD

**Issue by donger0616** [Alibaba-NLP/SeqGPT#2]
huanggingface上面没有，魔搭也没有找到下载的入口

**Comment by yiranyyu** [comment]
你好，可以在 https://huggingface.co/Yirany/SeqGPT-560M 或者 https://www.modelscope.cn/models/damo/nlp_seqgpt-560m/files 下载模型，相关信息在 [README](https://github.com/Alibaba-NLP/SeqGPT/tree/540ecec06e249402f526562ecae012aa7a62012f#checkpoints) 中可以找到

**Comment by donger0616** [comment]
已收到

**Comment by ttyuuuuuuuuuu** [comment]
![image](https://github.com/Alibaba-NLP/SeqGPT/assets/51437324/1666cabc-2591-4168-89cd-580d570a6d63)
我真没看到哪里下载模型

**Comment by yiranyyu** [comment]
> ![image](https://user-images.githubusercontent.com/51437324/264948051-1666cabc-2591-4168-89cd-580d570a6d63.png) 我真没看到哪里下载模型

你截图中的就是模型权重仓库，你可以根据[用例](https://huggingface.co/Yirany/SeqGPT-560M#uses)直接下载，下载的内容**就是截图中的**这些文件。当然你也可以直接点击图中的**下载图案**直接分别下载这些文件。
