### ISSUE TITLE
支持多标签分类吗？

### ISSUE THREAD

**Issue by JoshonSmith** [Alibaba-NLP/SeqGPT#5]
支持多标签分类吗？

**Comment by TTCoding** [comment]
可以进行多标签分类。模型的预置prompt并不限制标签数量。

**Comment by JoshonSmith** [comment]
> 可以进行多标签分类。模型的预置prompt并不限制标签数量。

抱歉，我还是没有从论文和代码中 找到合适的prompt用于多标签分类，能否提供一个例子
非常感谢

**Comment by JoshonSmith** [comment]
> 可以进行多标签分类。模型的预置prompt并不限制标签数量。

zh-cls-fudan-news里面的样本：

"输入: 出席亚太经合组织领导人与工商咨询理事会代表对话会。
分类: Economy，Law，Politics
输出: ","Economy
"
比如这个样本，是不是可以设置多个标签，就可以用于训练多标签分类？

**Comment by jeffchy** [comment]
可以
