### ISSUE TITLE
更大版本的模型

### ISSUE THREAD

**Issue by xxllp** [Alibaba-NLP/SeqGPT#6]
不知道其他版本的模型后续是否开源，最小的这个明显效果很一般吧

**Comment by xxllp** [comment]
还有个问题：官方为啥没有基于一些中文的大模型进行训练？这块是否也有类似的模型可以使用

**Comment by JoshonSmith** [comment]
期待更大版本的模型

**Comment by JoshonSmith** [comment]
能开放论文中的 1B7 的模型吗？这个模型也不太大

**Comment by yiranyyu** [comment]
感谢关注，我们开放了 SeqGPT-3B 的 API 以满足更大规模模型的需要，https://help.aliyun.com/zh/dashscope/developer-reference/opennlu-api-details 。

**Comment by datalee** [comment]
你好，同求啊，7b版本或者3b的离线文件
